spring.application.name=backend
server.port=2004
server.servlet.context-path=/icondenim-be
spring.security.user.name=admin
spring.security.user.password=123456

spring.datasource.url=jdbc:postgresql://localhost:8888/icondenim
spring.datasource.username=postgres
spring.datasource.password=Haitank4
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=83340abc94f82df094f6e59913934e67e707ebf8a008c76cbb717e0518db3542
jwt.access-token-expiration=15
jwt.refresh-token-expiration=7
jwt.access-token-name=accessToken
jwt.refresh-token-name=refreshToken